services:
  postgres:
    image: postgres:16-alpine
    container_name: petshop-postgres
    environment:
      POSTGRES_USER: petshop_admin
      POSTGRES_PASSWORD: petshop_password
      POSTGRES_DB: petshop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: