spring.application.name=pet-shop-api

spring.docker.compose.file=pet-shop-api/compose.yaml

spring.datasource.url=jdbc:postgresql://localhost:5432/petshop_db
spring.datasource.username=petshop_admin
spring.datasource.password=petshop_password
spring.jpa.hibernate.ddl-auto=update